return {

Riflesquad = {
	["Cost"] = 100,
	["MaxSoldiers"] = 4,
	["SoldierType"] = "Rifle",
},
Snipersquad = {
	["Cost"] = 150,
	["MaxSoldiers"] = 2,
	["SoldierType"] = "Sniper",
},
LMGsquad = {
	["Cost"] = 125,
	["MaxSoldiers"] = 3,
	["SoldierType"] = "LMG",
},
Shotgunsquad = {
	["Cost"] = 120,
	["MaxSoldiers"] = 3,
	["SoldierType"] = "Shotgun",
},
-- TankSquad = {
-- 	["Cost"] = 300,
-- 	["MaxSoldiers"] = 1,
-- 	["SoldierType"] = "tankoperator",
-- },
-- MixedSquad = {
-- 	["Cost"] = 200,
-- 	["MaxSoldiers"] = 5,
-- 	["SoldierType"] = "Mixed",
-- },
-- class.EmptySquad = {
-- 	["Cost"] = 0,
-- 	["MaxSoldiers"] = 0,
-- 	["SoldierType"] = "None",
-- },

 
}