return {
	["stepY"] = 0,
	["stepX"] = 0,
	["stepLength"] = 1,
	["stepSpacing"] = 1,
	["turnCounter"] = 1,
	["stepDirection"] = 0,
	["whatStepIsItOn"] = 1,
	["maxSteps"] = 50,
	["selected"] = nil,
	["raycastParams"] = nil,
	["newposition"] = nil,
	["HealingTeammate"] = nil,
	["PlacingWall"] = nil,
	["region"] = {
		Vector3.new(456, 66, 548) / 2,
		-Vector3.new(456, 66, 548) / 2,
	},
	squad = {},
	squadData = {},
}
